// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdqipFLarsdHsxfz1eT3aBg0XZv5kv4E4',
    appId: '1:333018391428:web:8bd6f77b4e8fb96ef3f3d1',
    messagingSenderId: '333018391428',
    projectId: 'waterstation-3464b',
    authDomain: 'waterstation-3464b.firebaseapp.com',
    storageBucket: 'waterstation-3464b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADj2dNmoywCzMbPB_0ovoToUodnIwSWpY',
    appId: '1:333018391428:android:8b06d2c816704976f3f3d1',
    messagingSenderId: '333018391428',
    projectId: 'waterstation-3464b',
    storageBucket: 'waterstation-3464b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD36kmeia7bBwaBuwTBrb83tFfHLFp1f3k',
    appId: '1:333018391428:ios:090bde7866c583c8f3f3d1',
    messagingSenderId: '333018391428',
    projectId: 'waterstation-3464b',
    storageBucket: 'waterstation-3464b.firebasestorage.app',
    iosBundleId: 'com.example.waterstationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD36kmeia7bBwaBuwTBrb83tFfHLFp1f3k',
    appId: '1:333018391428:ios:090bde7866c583c8f3f3d1',
    messagingSenderId: '333018391428',
    projectId: 'waterstation-3464b',
    storageBucket: 'waterstation-3464b.firebasestorage.app',
    iosBundleId: 'com.example.waterstationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdqipFLarsdHsxfz1eT3aBg0XZv5kv4E4',
    appId: '1:333018391428:web:95c43f3f55613c46f3f3d1',
    messagingSenderId: '333018391428',
    projectId: 'waterstation-3464b',
    authDomain: 'waterstation-3464b.firebaseapp.com',
    storageBucket: 'waterstation-3464b.firebasestorage.app',
  );
}
